import tkinter as tk
from tkinter import messagebox, simpledialog, ttk
import sqlite3
import os
from datetime import datetime

# --- Configuration ---
# Matches the SQLite database file generated by your server
DB_FILE = 'soshal.db'

class SoshalAdminPanel:
    def __init__(self, root):
        self.root = root
        self.root.title("Soshal Server Admin Panel (SQL Edition)")
        self.root.geometry("900x600")
        self.root.minsize(800, 500)
        
        self.current_selected_user = None
        
        self.setup_ui()
        self.check_database()

    def check_database(self):
        """Ensures the SQL database exists before allowing interactions."""
        if not os.path.exists(DB_FILE):
            messagebox.showwarning(
                "Database Not Found", 
                f"Could not find '{DB_FILE}'.\n\nPlease ensure your Soshal API Server has been started at least once to automatically create and migrate the database."
            )
        else:
            self.filter_users()

    def setup_ui(self):
        # --- Left Panel (User List & Search) ---
        left_frame = tk.Frame(self.root, padx=10, pady=10, width=250)
        left_frame.pack(side=tk.LEFT, fill=tk.Y)
        left_frame.pack_propagate(False) # Maintain width

        tk.Label(left_frame, text="Registered Users", font=("Arial", 12, "bold")).pack(anchor=tk.W, pady=(0, 5))
        
        # Search Bar
        search_frame = tk.Frame(left_frame)
        search_frame.pack(fill=tk.X, pady=(0, 5))
        tk.Label(search_frame, text="Search:", font=("Arial", 9)).pack(side=tk.LEFT)
        self.search_var = tk.StringVar()
        
        # Real-time SQL filtering as you type
        self.search_var.trace_add("write", self.filter_users)
        
        self.search_entry = tk.Entry(search_frame, textvariable=self.search_var)
        self.search_entry.pack(side=tk.LEFT, fill=tk.X, expand=True, padx=(5, 0))

        # Scrollbar and Listbox for Users
        list_frame = tk.Frame(left_frame)
        list_frame.pack(fill=tk.BOTH, expand=True)
        
        scrollbar = tk.Scrollbar(list_frame)
        scrollbar.pack(side=tk.RIGHT, fill=tk.Y)
        
        self.user_listbox = tk.Listbox(list_frame, yscrollcommand=scrollbar.set, font=("Arial", 11))
        self.user_listbox.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)
        scrollbar.config(command=self.user_listbox.yview)
        
        self.user_listbox.bind('<<ListboxSelect>>', self.on_user_select)

        # Refresh Button
        tk.Button(left_frame, text="Refresh DB", command=self.filter_users).pack(fill=tk.X, pady=(5, 0))

        # --- Right Panel (Controls & Posts) ---
        self.right_frame = tk.Frame(self.root, padx=20, pady=10)
        self.right_frame.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)

        # --- 1. User Controls Center ---
        controls_frame = tk.Frame(self.right_frame)
        controls_frame.pack(fill=tk.X, pady=(0, 10))

        tk.Label(controls_frame, text="User Controls", font=("Arial", 12, "bold")).pack(anchor=tk.W, pady=(0, 10))

        # Username Display & Suffix ID & Rename
        tk.Label(controls_frame, text="Username:", font=("Arial", 10)).pack(anchor=tk.W)
        name_frame = tk.Frame(controls_frame)
        name_frame.pack(fill=tk.X, pady=(0, 10))
        
        self.lbl_username_val = tk.Label(name_frame, text="Select a user...", font=("Arial", 11, "italic"), fg="gray")
        self.lbl_username_val.pack(side=tk.LEFT)
        
        # Unique User ID Suffix label
        self.lbl_userid_val = tk.Label(name_frame, text="", font=("Arial", 11, "bold"), fg="#8b5cf6")
        self.lbl_userid_val.pack(side=tk.LEFT, padx=(5, 0))
        
        self.btn_rename = tk.Button(name_frame, text="Rename User", state=tk.DISABLED, command=self.rename_user)
        self.btn_rename.pack(side=tk.RIGHT)

        # Password Hash Display
        tk.Label(controls_frame, text="Password Hash (PBKDF2):", font=("Arial", 10)).pack(anchor=tk.W)
        pass_frame = tk.Frame(controls_frame)
        pass_frame.pack(fill=tk.X, pady=(0, 10))
        
        self.entry_password = tk.Entry(pass_frame, show="*", font=("Arial", 10), state="readonly")
        self.entry_password.pack(side=tk.LEFT, fill=tk.X, expand=True, padx=(0, 10))
        
        self.btn_toggle_pass = tk.Button(pass_frame, text="Show", state=tk.DISABLED, command=self.toggle_password)
        self.btn_toggle_pass.pack(side=tk.RIGHT)

        # Stats & Delete Button
        stats_frame = tk.Frame(controls_frame)
        stats_frame.pack(fill=tk.X, pady=(5, 10))
        self.lbl_stats = tk.Label(stats_frame, text="Posts: 0 | Followers: 0 | Following: 0", font=("Arial", 10))
        self.lbl_stats.pack(side=tk.LEFT)

        self.btn_delete = tk.Button(stats_frame, text="Delete User & ALL Posts", bg="#ffcccc", fg="#cc0000", font=("Arial", 10, "bold"), state=tk.DISABLED, command=self.delete_user)
        self.btn_delete.pack(side=tk.RIGHT)

        tk.Frame(self.right_frame, height=2, bd=1, relief=tk.SUNKEN).pack(fill=tk.X, pady=10)

        # --- 2. User Posts List Section ---
        tk.Label(self.right_frame, text="User's Posts History", font=("Arial", 12, "bold")).pack(anchor=tk.W, pady=(0, 5))
        
        posts_list_frame = tk.Frame(self.right_frame)
        posts_list_frame.pack(fill=tk.BOTH, expand=True, pady=(0, 10))
        
        post_scroll = tk.Scrollbar(posts_list_frame)
        post_scroll.pack(side=tk.RIGHT, fill=tk.Y)
        
        self.posts_listbox = tk.Listbox(posts_list_frame, yscrollcommand=post_scroll.set, font=("Courier", 10))
        self.posts_listbox.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)
        post_scroll.config(command=self.posts_listbox.yview)

    def filter_users(self, *args):
        """Filters the user list directly via SQL LIKE queries."""
        if not os.path.exists(DB_FILE): return
        
        query = self.search_var.get().lower()
        self.user_listbox.delete(0, tk.END)
        
        try:
            with sqlite3.connect(DB_FILE) as conn:
                cursor = conn.cursor()
                cursor.execute('SELECT username FROM users WHERE LOWER(username) LIKE ? ORDER BY username', (f"%{query}%",))
                for row in cursor.fetchall():
                    self.user_listbox.insert(tk.END, row[0])
        except Exception as e:
            print(f"DB Read Error: {e}")

    def load_user_posts(self, username):
        """Fetches posts sequentially from the SQL Database indexing structure."""
        self.posts_listbox.delete(0, tk.END)

        try:
            with sqlite3.connect(DB_FILE) as conn:
                cursor = conn.cursor()
                cursor.execute('''
                    SELECT id, content, image, timestamp 
                    FROM posts 
                    WHERE author = ? 
                    ORDER BY timestamp DESC
                ''', (username,))
                
                rows = cursor.fetchall()
                
                for row in rows:
                    post_id, content, image, ts = row
                    date_str = datetime.fromtimestamp(ts).strftime('%Y-%m-%d %H:%M:%S')
                    
                    # Clean up content for preview
                    content_snippet = content.replace('\n', ' ') if content else ''
                    if len(content_snippet) > 60:
                        content_snippet = content_snippet[:57] + "..."
                    if not content_snippet and image:
                        content_snippet = "[IMAGE POST]"
                        
                    display_str = f"[{date_str}] ID: {post_id[:8]}... | {content_snippet}"
                    self.posts_listbox.insert(tk.END, display_str)
        except Exception as e:
            print(f"Error loading posts: {e}")

    def on_user_select(self, event):
        """Handles selecting a user from the list and fires targeted SQL data aggregations."""
        selection = self.user_listbox.curselection()
        if not selection: return
            
        username = self.user_listbox.get(selection[0])
        self.current_selected_user = username

        try:
            with sqlite3.connect(DB_FILE) as conn:
                cursor = conn.cursor()
                
                # Get User Details
                cursor.execute('SELECT user_id, password_hash FROM users WHERE username = ?', (username,))
                user_row = cursor.fetchone()
                if not user_row: return
                user_id, pwd_hash = user_row

                # Aggregate Counts Fast via indexes
                cursor.execute('SELECT COUNT(*) FROM follows WHERE following = ?', (username,))
                followers = cursor.fetchone()[0]

                cursor.execute('SELECT COUNT(*) FROM follows WHERE follower = ?', (username,))
                following = cursor.fetchone()[0]

                cursor.execute('SELECT COUNT(*) FROM posts WHERE author = ?', (username,))
                posts_count = cursor.fetchone()[0]

            # Update UI
            self.lbl_username_val.config(text=username, font=("Arial", 12, "bold"), fg="black")
            self.lbl_userid_val.config(text=f"#{user_id}")
            
            self.entry_password.config(state=tk.NORMAL)
            self.entry_password.delete(0, tk.END)
            self.entry_password.insert(0, pwd_hash)
            self.entry_password.config(state="readonly", show="*")
            self.btn_toggle_pass.config(text="Show")
            
            self.lbl_stats.config(text=f"Posts: {posts_count} | Followers: {followers} | Following: {following}")

            # Fetch chronological post previews
            self.load_user_posts(username)

            # Enable Control buttons
            self.btn_rename.config(state=tk.NORMAL)
            self.btn_toggle_pass.config(state=tk.NORMAL)
            self.btn_delete.config(state=tk.NORMAL)
            
        except Exception as e:
            messagebox.showerror("Database Error", f"Failed to retrieve user info: {e}")

    def clear_details(self):
        """Resets the entire right panel."""
        self.current_selected_user = None
        self.lbl_username_val.config(text="Select a user...", font=("Arial", 11, "italic"), fg="gray")
        self.lbl_userid_val.config(text="")
        
        self.entry_password.config(state=tk.NORMAL)
        self.entry_password.delete(0, tk.END)
        self.entry_password.config(state="readonly", show="*")
        
        self.lbl_stats.config(text="Posts: 0 | Followers: 0 | Following: 0")
        
        self.btn_rename.config(state=tk.DISABLED)
        self.btn_toggle_pass.config(state=tk.DISABLED, text="Show")
        self.btn_delete.config(state=tk.DISABLED)
        
        self.posts_listbox.delete(0, tk.END)

    def toggle_password(self):
        """Toggles the visibility of the password hash entry."""
        if self.entry_password.cget('show') == '*':
            self.entry_password.config(show='')
            self.btn_toggle_pass.config(text="Hide")
        else:
            self.entry_password.config(show='*')
            self.btn_toggle_pass.config(text="Show")

    def rename_user(self):
        """Safely renames a user using SQL cascades and transactional safety."""
        old_name = self.current_selected_user
        if not old_name: return

        new_name = simpledialog.askstring("Rename User", f"Enter new username for '{old_name}':", parent=self.root)
        
        if not new_name or new_name.strip() == "" or new_name == old_name:
            return
            
        new_name = new_name.strip()
        
        try:
            with sqlite3.connect(DB_FILE) as conn:
                cursor = conn.cursor()
                
                # Check Availability
                cursor.execute('SELECT 1 FROM users WHERE LOWER(username) = LOWER(?)', (new_name,))
                if cursor.fetchone():
                    messagebox.showerror("Error", "That username is already taken.")
                    return

                # Perform universal SQL rename
                cursor.execute('UPDATE users SET username = ? WHERE username = ?', (new_name, old_name))
                cursor.execute('UPDATE posts SET author = ? WHERE author = ?', (new_name, old_name))
                cursor.execute('UPDATE follows SET follower = ? WHERE follower = ?', (new_name, old_name))
                cursor.execute('UPDATE follows SET following = ? WHERE following = ?', (new_name, old_name))
                conn.commit()

                # Tally up modifications
                cursor.execute('SELECT COUNT(*) FROM posts WHERE author = ?', (new_name,))
                posts_updated = cursor.fetchone()[0]

            messagebox.showinfo("Success", f"User renamed to '{new_name}'.\nUpdated {posts_updated} posts in the database.")
            self.filter_users()
            self.clear_details()
            
        except Exception as e:
            messagebox.showerror("Transaction Failed", f"Could not rename user: {e}")

    def delete_user(self):
        """Executes a hard wipe of a user and all associatons directly via SQL."""
        target = self.current_selected_user
        if not target: return

        confirm = messagebox.askyesno("WARNING", f"Are you sure you want to PERMANENTLY delete '{target}'?\n\nThis will instantly wipe their account and EVERY post they have ever made from the database. This cannot be undone.", icon='warning')
        
        if not confirm: return

        try:
            with sqlite3.connect(DB_FILE) as conn:
                cursor = conn.cursor()
                
                # Count before wiping
                cursor.execute('SELECT COUNT(*) FROM posts WHERE author = ?', (target,))
                posts_deleted = cursor.fetchone()[0]

                # Hard wipe
                cursor.execute('DELETE FROM users WHERE username = ?', (target,))
                cursor.execute('DELETE FROM posts WHERE author = ?', (target,))
                cursor.execute('DELETE FROM follows WHERE follower = ? OR following = ?', (target, target))
                conn.commit()

            messagebox.showinfo("Deleted", f"User '{target}' has been deleted.\n{posts_deleted} posts were permanently removed.")
            self.filter_users()
            self.clear_details()
            
        except Exception as e:
            messagebox.showerror("Deletion Error", f"Failed to completely wipe user: {e}")

if __name__ == "__main__":
    root = tk.Tk()
    app = SoshalAdminPanel(root)
    root.mainloop()